### ISSUE TITLE
port over ptrarchive

### ISSUE THREAD

**Issue by picatz** [subfinder/research#27]
https://github.com/subfinder/subfinder/tree/master/libsubfinder/sources/ptrarchive

**Comment by picatz** [comment]
> **Note**: this resources don't support `https`, which makes me not like it very much. 👎

**Comment by picatz** [comment]
@Mzack9999 @codingo @Ice3man543 Should we be supporting sources that are being served insecurely? 🤔

**Comment by Ice3man543** [comment]
I believe it provides some results hence there is nothing much wrong with this source. :)
