### ISSUE TITLE
Aggregating/Filtering Results

### ISSUE THREAD

**Issue by picatz** [subfinder/research#3]
As a  [**`Result`**](https://github.com/subfinder/research/blob/master/result.go) moves along through our code, we probably want to direct it in a variety of different ways. 

For example, perhaps a command-line setting says "I only want domains that match this regex", or "split up results into their own files (per domain)", ect. We want to be able to easily orchestrate these things.

So I propose an aggregator (a filter):
> This is a "custom" one which allows you to pass in your own function that returns a boolean. If the function returns true, the `Result` is sent along the out channel.
```go
func AggregateCustomResults(in chan *Result, custom func(r *Result) bool) <-chan *Result {
	out := make(chan *Result)
	go func(in, out chan *Result) {
		defer close(out)
		for result := range in {
			if custom(result) {
				out <- result
			}
		}
	}(in, out)
	return out
}
```
## Example Usage
```go
for result := range AggregateCustomResults(fakeResultsChan, func(r *Result) bool {
		// find success values that are strings only
		_, ok := r.Success.(string)
		return ok
	}) {
		// "safely" check stringy things on those results
		if result.Success.(string) != "wiggle" {
			fmt.Println(r.Success)
		}
	}
}
```

**Comment by Ice3man543** [comment]
Nice idea. It is really needed and would make this easier definitely.

**Comment by picatz** [comment]
👌Glad you agree @Ice3man543! 

I'll make a PR and start working on this feature today. Of course, anyone else is still free to raise concerns/objections.
