### ISSUE TITLE
investigate command-line application framework choices

### ISSUE THREAD

**Issue by picatz** [subfinder/research#44]
We should figure out which direction we want to go in to provide a classier, more robust command-line application experience for users in v2. [There are a few golang command-line application framework choices we may want to consider](https://github.com/avelino/awesome-go#command-line), starting with:
* [`cobra`](https://github.com/spf13/cobra)
* [`urfave`](https://github.com/urfave/cli)
* [`odin`](https://github.com/jwaldrip/odin)

I've used [`urfave`](https://github.com/urfave/cli) before, and really liked it. I'm currently experimenting with [`cobra`](https://github.com/spf13/cobra), though I'm open to something else.

**Comment by Ice3man543** [comment]
I suggest we use cobra. It seems like a well tested framework and the community standard at the moment.

**Comment by picatz** [comment]
@codingo @Mzack9999 Do either of you have any thoughts on this?

**Comment by picatz** [comment]
A basic, working cobra command-line application has been merged in master with https://github.com/subfinder/research/pull/46

# Install 
```shell
$ go get github.com/subfinder/research/subzero
```

# Usage
```shell
$ subzero 
```
```
Usage:
  subzero [command]

Available Commands:
  enumerate   Enumerate subdomains for the given domains.
  help        Help about any command

Flags:
  -h, --help   help for subzero

Use "subzero [command] --help" for more information about a command.
```
You can use the `enumerate` command to enumerate 1 or more domains subdomains with the currently ported over sources. 
```
$ subzero enumerate google.com --verbose
```

**Comment by picatz** [comment]
I think we're going to end up using cobra. 🐍
