### ISSUE TITLE
use google search completions

### ISSUE THREAD

**Issue by picatz** [subfinder/research#73]
Using google search completions could be an interesting source.

Given the domain `google.com`:
`http://suggestqueries.google.com/complete/search?output=toolbar&hl=en&q=google.com`

I started getting some interesting results when playing around manually.

**Comment by picatz** [comment]
Oh, look, json! 

`curl "https://www.google.com/complete/search?output=search&client=chrome&q=apple.com" | jq .`

**Comment by picatz** [comment]
Fixed with https://github.com/subfinder/research/commit/0269184cf41119717b7d5bfc3b995f6926c651a6

**Comment by Ice3man543** [comment]
Wow. This is definitely very interesting source. Kudos @picat. :okay:

**Comment by picatz** [comment]
Glad you like it @Ice3man543! 🙌
